language: node_js
sudo: required
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install: true
before_script:
- export DOCKER_HOST="$HOST_NAME"
script:
- docker build -t tuchphon/htmltest .
- docker push tuchphon/htmltest
after_success:
- docker stop htmltest
- docker rm htmltest
- docker run -p 8088:80 -d --name htmltest tuchphon/htmltest:latest
service: docker
env:
  global:
  - secure: Xw1OOJPDZFgpW8aoS+Jk0qiVFiACn53OyTHjKyyN6TLGj23BHFmGa5opstiRRVGpPObxIDBjHxt0AU+Oz4S7keNys9N3dKqdm29+5OlzRN252A8kdfPeOLl+R++xONqn1QDMx31oIWgXtUm2bUrntdkW2p6TGcptRqwJ3Jjr8ZuK78yF6v5Spz/WEBMU1g4NCawto2k4jd24RbZGlNCyopkStyrltxfq+RMoBoQQTWsFA76HE8wV7GFyVmYF1NPPFYaafrB+0yLGIzqIoGgh2pceYub/CySUPTwZKXrSHiO/UfPzyjylrZAifrKR7zASiUctl+hWYX5k4nP9nHUg1JcqTSxAZ7arMNlWbu2zjGuhhSGoDBdkG8C7qHEn7/9fcA2OlAm2bdHnu5Ha56VQ4bF6mfOklaCGUqysC3nAgKG9doOgBYYzCtyLLLII5V6e6FUPjKfboie33XkmtHOCOvWXhKlDMAzxfcZtoYQoEB8NlCbxRsXnkfpXx6B0MvxJM4aPsk5/OW6VqE5oFV3uIKyavtKuYlHRhuLIri27bhaxph2GtZ/MHvm0lKk20tJ5Tl8eRt/ZwelP7AnW5yKW5jzX8SlXdjSwTCb0GjPyNMp2JoMbiAeUHaV5wDzbHvh0IEe9Pk+cErXxzrMhQaTdkjuCxKdJPfp/L2gR4qXH8rg=
  - secure: pIUy7Ir0Y9L+TdR9BXQ1J2Y+nsXyfVDXwZQsBsKOC4Rsxlpe88enrUuEiYWcaEr3QrIN+YTCkUpUhKBRK5X6HkTAHs7R1iNPBBDQIXLsIY9Pr3j05iPRfAorfPh0s25eElBIUJqpIa0WFBuYWvwEk4DO14B/uLKYiAnnCdIBHELrfPS7/5uWKWzMDdbanl0tJANyCwZLSrZiYBKAc0I+FA93Hs6Cojb8qZcG/oL9FCpa695T1LeVLC83hEyDFfgjkacctl1g3ZqIofOOpPYsEu2zeBMIIlDp/V0TTi4VQfazwa9K/7XX+B9A7nb0Ue9SGLVDgV2lkopYYq4LSbgVFWbgEG0dgIIYQDE2oTr1IKpX2WE4bE+Aq6xPm6FUA6fZBY1mYkNPC3Qg2BtNBqVnBbaIUPP+JOtKY81vYeuoZJheFp7FmYRY22XlbthDmp7ZqYN1Jn7rLTo6quoJDBctgBZdFVQnzMAwZThbJFwAjW02CRBGS98G5PYOtY6T6cUoZd2DUlIyZ80yGcH/uyT8OR+DdCZd+T1+7xuSI5YL6bWX7UtlI7Ep9jWSHKW72cAn/EANZjOMKn/3E6Bd2+kEBlMofDJ1MCNXMuNMOAbcDJjQQSzLYQt5Wv3G78pTHI7hyWue56zXj1EuzBJFuyQJmQWRYpChMjhneVHbgAu6EQ4=
  - secure: U8VHlw90CkJo42V1yOs6ULq8jknYalOpPGpTBA7p3VHbGg0U+qwCrJ0/g8VOvFk9mFZTJ1w0zPs5m6HLL4XaVT62B2UljzL17+u7oZqgzOqXS/xn6P4gxAMQxGu8CYc9LQBYRK7op9+9f/EF0wXx4SqQwCtJjUNAPDGHDzPgYZNgO7fCKMBmBkmgwx5JdDhuU5yVM0amwOjvy5noIshYaeoN/6G8KJaE/jEMXMIyAzCO/WxVBeqIwwiGCpUUjXxm1d7Jw2l+z3f3KbUicrm9zsE5q/jHktowzpBm7ZHWcu1e6Gf63tlNeRWRHSLEEncx6Zroqhow4170a/NyocFPIXpxqCFDMe6lqWjHQQkJFkuFZ5m+601gFsd9r2icGfVt5eX1/+7LzIJzML8+jOS/t95C9sspYW5kUdrpSf1doWOJlcReIEeOwGTkfMI6jfwfiXclllaQzx+9I8Qczr6iVjL5uiypJzOiKBVFD21U9WLV9uL/rmd+gZ7zXp9NxXzNo0HAVubVkUCGZ1gpZvAKYMWv7serD/ZIXYuoAXdb7qlNGBgSCGE7jH4BYWoeB8vhdRl2c6hF3l2yHC9U002TJFZJ3a2geX8MDBBVrIH6GpKj61u6xu7TKlA3SJsVYjVs8zjAzEByli9h/KZW+8dYsteo+DZyQKrZWcvO1roQx+4=
